id: PE29F93B3
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13376
  instance_id: http://purl.bdrc.io/resource/IE3JT13376
  collection_id: http://purl.bdrc.io/resource/PR0ET010
  language_id: None
  title:
    bo:
    - མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་དབྱིག་གཉེན་ཞལ་ལུང་།
  alt_title:
    bo:
    - དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་ལེགས་པར་བཤད་པ་དབྱིག་གཉེན་ཞལ་ལུང་ས་བཅད་དང་བཅས་པ།
  author: None
  publisher: Various
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    f45ec6841f8a495990c8565f0b660937:
      title: ༄༅།་།སྲིད་པའི་འཇིགས་པ་ལས་སྐྱོབས་ཤིང༌།་།རྣམ་གྲོལ་བགྲོད་པའི་ལམ་གཅིག་པུ།་།ལུང་རྟོགས་གཉིས་བསྡུས་ཞི་བསིལ་ཆོས།་།གུས་པའི་ཕྱག་གི་ཡུལ
      volume_number: 1
      base_file: UT3JT13376_001_0001.txt
      reference: http://purl.bdrc.io/resource/VL148DF01EADEE9347
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-31T08:21:10.969730'
last_modified_at: '2021-12-31T08:21:10.969737'
